sudo: required
services:
  - docker

before_install:
  - docker build -t prinjor/react-test -f ./client/Dockerfile.dev ./client

script:
  # - docker run prinjor/react-test npm test -- --coverage
  - docker run -e CI=true prinjor/react-test npm test

after_success:
  - docker build -t prinjor/multi-client ./client
  - docker build -t prinjor/multi-nginx ./nginx
  - docker build -t prinjor/multi-server ./server
  - docker build -t prinjor/multi-worker ./worker