name: Docker course with react

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build and Test React app
        run: |
          docker build -t prinjor/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true prinjor/react-test npm test
      
      - name: Build and push images to Docker Hub
        run: |
          docker build -t prinjor/multi-client ./client
          docker build -t prinjor/multi-nginx ./nginx
          docker build -t prinjor/multi-server ./server
          docker build -t prinjor/multi-worker ./worker
          
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin
          
          docker push prinjor/multi-client
          docker push prinjor/multi-nginx
          docker push prinjor/multi-server
          docker push prinjor/multi-worker
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to ElasticBeanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: 'prinjor-multi-docker'
          environment_name: 'Prinjor-multi-docker-env'
          version_label: ${{ github.sha }}
          region: us-east-2
          deployment_package: deploy.zip 
          existing_bucket_name: elasticbeanstalk-us-east-2-332150451947